---
extends: airbnb
parser: babel-eslint

plugins:
  - jest

env:
  jest/globals: true

globals:
  FormData: true

rules:
  max-len: [error, 120]

  no-tabs: off
  indent:
    - error
    - tab
    - SwitchCase: 1

  jsx-quotes: [error, prefer-single]
  react/jsx-one-expression-per-line: off
  react/jsx-filename-extension: off
  react/jsx-indent: [error, tab]
  react/jsx-indent-props: [error, tab]
  jsx-a11y/no-autofocus: off
  jsx-a11y/label-has-associated-control: off
  jsx-a11y/label-has-for: off
  jsx-a11y/interactive-supports-focus: off
  jsx-a11y/click-events-have-key-events: off
  react/destructuring-assignment: [always, { ignoreClassFields: true }]

settings:
  import/core-modules: [assets]
